### ISSUE TITLE
Prevent user from saving already saved schedule

### ISSUE THREAD

**Issue by miguelHx** [dragonbone81/bobcat-courses-backend#16]
In rest api, consider sending back message "this schedule has already been saved" or something along those lines.

**Comment by dragonbone81** [comment]
should be fixed.
simple explanation is in the api but basically it will give you this if schedule exists.
{'schedule_index': index, 'error': 'Schedule already exits', 'type': 'already_exists'}

Index starts at 0.
![capture](https://user-images.githubusercontent.com/23389970/44181923-60e7d480-a0b9-11e8-9eab-7420a01e08d1.PNG)
